
package co.gov.crcom.mycroft.schema;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IServiceldap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IServiceldap {


    /**
     * 
     * @param usuario
     * @param pwd
     * @return
     *     returns co.gov.crcom.mycroft.schema.RespuestaDTO
     */
    @WebMethod(action = "http://tempuri.org/IServiceldap/autenticacion")
    @WebResult(name = "autenticacionResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "autenticacion", targetNamespace = "http://tempuri.org/", className = "co.gov.crcom.mycroft.schema.Autenticacion")
    @ResponseWrapper(localName = "autenticacionResponse", targetNamespace = "http://tempuri.org/", className = "co.gov.crcom.mycroft.schema.AutenticacionResponse")
    public RespuestaDTO autenticacion(
        @WebParam(name = "usuario", targetNamespace = "http://tempuri.org/")
        String usuario,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        String pwd);

    /**
     * 
     * @param usuario
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(action = "http://tempuri.org/IServiceldap/existeusuario")
    @WebResult(name = "existeusuarioResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "existeusuario", targetNamespace = "http://tempuri.org/", className = "co.gov.crcom.mycroft.schema.Existeusuario")
    @ResponseWrapper(localName = "existeusuarioResponse", targetNamespace = "http://tempuri.org/", className = "co.gov.crcom.mycroft.schema.ExisteusuarioResponse")
    public Boolean existeusuario(
        @WebParam(name = "usuario", targetNamespace = "http://tempuri.org/")
        String usuario);

}
