
package co.gov.crcom.mycroft.schema;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServiceldapCRC", targetNamespace = "http://tempuri.org/", wsdlLocation = "file:/D:/IDIAZ/Desarrollo/WK_CRC/crcback/src/main/resources/wsdl/ServiceldapCRC.wsdl")
public class ServiceldapCRC
    extends Service
{

    private final static URL SERVICELDAPCRC_WSDL_LOCATION;
    private final static WebServiceException SERVICELDAPCRC_EXCEPTION;
    private final static QName SERVICELDAPCRC_QNAME = new QName("http://tempuri.org/", "ServiceldapCRC");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/IDIAZ/Desarrollo/WK_CRC/crcback/src/main/resources/wsdl/ServiceldapCRC.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICELDAPCRC_WSDL_LOCATION = url;
        SERVICELDAPCRC_EXCEPTION = e;
    }

    public ServiceldapCRC() {
        super(__getWsdlLocation(), SERVICELDAPCRC_QNAME);
    }

    public ServiceldapCRC(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICELDAPCRC_QNAME, features);
    }

    public ServiceldapCRC(URL wsdlLocation) {
        super(wsdlLocation, SERVICELDAPCRC_QNAME);
    }

    public ServiceldapCRC(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICELDAPCRC_QNAME, features);
    }

    public ServiceldapCRC(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiceldapCRC(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IServiceldap
     */
    @WebEndpoint(name = "BasicHttpBinding_IServiceldap")
    public IServiceldap getBasicHttpBindingIServiceldap() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IServiceldap"), IServiceldap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IServiceldap
     */
    @WebEndpoint(name = "BasicHttpBinding_IServiceldap")
    public IServiceldap getBasicHttpBindingIServiceldap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IServiceldap"), IServiceldap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICELDAPCRC_EXCEPTION!= null) {
            throw SERVICELDAPCRC_EXCEPTION;
        }
        return SERVICELDAPCRC_WSDL_LOCATION;
    }

}
